const elevi = [
    {
      nume: "Popescu",
      prenume: "Ion",
      dataNasterii: "2004-05-15",
      clasa: "12A",
      email: "ion.popescu@example.com",
      mediaGenerala: 9.5,
      ID: 1,
    },
    {
      nume: "Ionescu",
      prenume: "Ana",
      dataNasterii: "2005-02-28",
      clasa: "11B",
      email: "ana.ionescu@example.com",
      mediaGenerala: 9.8,
      ID: 2,
    },
    {
      nume: "Constantinescu",
      prenume: "Mihai",
      dataNasterii: "2004-09-10",
      clasa: "10C",
      email: "mihai.constantinescu@example.com",
      mediaGenerala: 9.2,
      ID: 3,
    },
    {
      nume: "Georgescu",
      prenume: "Maria",
      dataNasterii: "2003-11-20",
      clasa: "12B",
      email: "maria.georgescu@example.com",
      mediaGenerala: 9.6,
      ID: 4, 
    },
    {
      nume: "Popa",
      prenume: "Andrei",
      dataNasterii: "2004-07-18",
      clasa: "11A",
      email: "andrei.popa@example.com",
      mediaGenerala: 9.4,
      ID: 5,
    },
    {
      nume: "Dumitrescu",
      prenume: "Elena",
      dataNasterii: "2005-01-03",
      clasa: "10B",
      email: "elena.dumitrescu@example.com",
      mediaGenerala: 9.7,
      ID: 6,
    },
    {
      nume: "Radulescu",
      prenume: "George",
      dataNasterii: "2004-08-25",
      clasa: "12C",
      email: "george.radulescu@example.com",
      mediaGenerala: 9.3,
      ID: 7,
    },
    {
      nume: "Popescu",
      prenume: "Ioana",
      dataNasterii: "2004-04-12",
      clasa: "11A",
      email: "ioana.popescu@example.com",
      mediaGenerala: 9.8,
      ID: 8, 
    },
    {
      nume: "Stoica",
      prenume: "Andreea",
      dataNasterii: "2005-07-07",
      clasa: "10C",
      email: "andreea.stoica@example.com",
      mediaGenerala: 9.6,
      ID: 9,
    },
    {
      nume: "Gheorghe",
      prenume: "Alexandru",
      dataNasterii: "2004-10-30",
      clasa: "12A",
      email: "alexandru.gheorghe@example.com",
      mediaGenerala: 9.5,
      ID: 10,
    },
    {
      nume: "Dobre",
      prenume: "Ana-Maria",
      dataNasterii: "2003-12-05",
      clasa: "11B",
      email: "ana-maria.dobre@example.com",
      mediaGenerala: 9.9,
      ID: 11,
    },
    {
      nume: "Cristea",
      prenume: "Cristian",
      dataNasterii: "2004-02-18",
      clasa: "10C",
      email: "cristian.cristea@example.com",
      mediaGenerala: 9.7,
      ID: 12, 
    },
    {
      nume: "Gheorghiu",
      prenume: "Alina",
      dataNasterii: "2004-06-23",
      clasa: "12B",
      email: "alina.gheorghiu@example.com",
      mediaGenerala: 9.2,
      ID: 13,
    },
    {
      nume: "Iancu",
      prenume: "Mihai",
      dataNasterii: "2005-03-11",
      clasa: "11A",
      email: "mihai.iancu@example.com",
      mediaGenerala: 9.4,
      ID: 14, 
    },
    {
      nume: "Florescu",
      prenume: "Elena",
      dataNasterii: "2004-09-29",
      clasa: "10B",
      email: "elena.florescu@example.com",
      mediaGenerala: 9.8,
      ID: 15, 
    },
    {
      nume: "Vasilescu",
      prenume: "Andrei",
      dataNasterii: "2003-11-16",
      clasa: "12C",
      email: "andrei.vasilescu@example.com",
      mediaGenerala: 9.6,
      ID: 16, 
    },
    {
      nume: "Dinu",
      prenume: "Cristina",
      dataNasterii: "2004-07-25",
      clasa: "11A",
      email: "cristina.dinu@example.com",
      mediaGenerala: 9.3,
      ID: 17,
    },
    {
      nume: "Stancu",
      prenume: "Alexandru",
      dataNasterii: "2005-01-14",
      clasa: "10C",
      email: "alexandru.stancu@example.com",
      mediaGenerala: 9.7,
      ID: 18, 
    },
    {
      nume: "Ion",
      prenume: "Diana",
      dataNasterii: "2004-08-07",
      clasa: "12B",
      email: "diana.ion@example.com",
      mediaGenerala: 9.5,
      ID: 19, 
    },
    {
      nume: "Stan",
      prenume: "Andrei",
      dataNasterii: "2004-03-22",
      clasa: "11B",
      email: "andrei.stan@example.com",
      mediaGenerala: 9.9,
      ID: 20,
    },
  ];

  module.exports = { elevi };